### PR TITLE
bump k8s packages to 1.17.6

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by ZhiminXiang** [comment]
Does this mean in Knative 0.16, we will only support k8s 1.17 and above?

**Comment by dprotaso** [comment]
no k8s 1.17 packages support k8s 1.16

**Comment by dprotaso** [comment]
> Does this mean in Knative 0.16, we will only support k8s 1.17 and above?

The other factor is if K8s 1.19 is released (before Knative 0.16) then per the Knative release principles we'd support K8s 1.17 and higher

**Comment by ZhiminXiang** [comment]
/lgtm
/approve
Thanks for fixing it.

**Pull request merged**
